import Head from "next/head";
import React from "react";
import HomePage from "./HomePage";

export default function Home() {
    return (
        <React.Fragment>
            <Head>
                <title>NEXT APP</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <HomePage />
            </main>
        </React.Fragment>
    );
}
